name: Transcribe Episode

on:
  workflow_dispatch:
    inputs:
      episode_guid:
        description: "Episode GUID to transcribe"
        required: true
        type: string
      cleanup_method:
        description: "Cleanup method (groq or gemini)"
        required: true
        type: choice
        options:
          - groq
          - gemini
        default: groq

permissions:
  contents: write
  pull-requests: write

jobs:
  transcribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run transcription
        env:
          ASSEMBLYAI_API_KEY: ${{ secrets.ASSEMBLYAI_API_KEY }}
        run: npm run transcribe ${{ inputs.episode_guid }}

      - name: Cleanup transcript with AI
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: npx tsx scripts/cleanup-transcript.ts ${{ inputs.episode_guid }} ${{ inputs.cleanup_method }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          commit-message: "Add transcription for episode ${{ inputs.episode_guid }}"
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          signoff: false
          branch: transcribe-episode-${{ inputs.episode_guid }}
          delete-branch: true
          title: "Add transcription for episode ${{ inputs.episode_guid }}"
          body: |
            This PR adds transcription for episode ${{ inputs.episode_guid }}.

            **Transcription includes:**
            - Speaker identification
            - Timestamps
            - Full text of the episode
            - Japanese language support

            **AI Cleanup:**
            - Method: ${{ inputs.cleanup_method }}
            - Natural Japanese text (spaces removed)
            - Proper punctuation added
          labels: transcription
          draft: false
